FROM nginx:alpine

RUN apk add --no-cache bash jq

COPY docker/nginx.conf /etc/nginx/nginx.conf.template
COPY docker/generate-config-nginx.sh /generate-config.sh
COPY docker/entrypoint-nginx.sh /entrypoint.sh

RUN chmod +x /generate-config.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]

CMD ["nginx", "-g", "daemon off;"]